### ISSUE TITLE
Thanks from Prodction

### ISSUE THREAD

**Issue by D1no** [ds300/react-native-typescript-transformer#18]
Dear David, I just want to report back to you that we are using react-native-typescript-transformer successfully in production with ReactNative 0.45.1. Thank you very much for you effort in bringing this into react-native and maintaining this package. It made our stack incredibly more stable and predictable.

If you ever happen to be in Berlin, let me know for a sponsored beer.

Dino
Shoplink Team

**Comment by ds300** [comment]
😊 This feedback is so very nice to have, thank you! I do like to visit Berlin occasionally, will try to remember to hit you up next time.

I'm going to close this issue because it's not really an issue, but you totally made my day. :heart:
