### ISSUE TITLE
Is this working? Any examples?

### ISSUE THREAD

**Issue by cbrevik** [ds300/react-native-typescript-transformer#2]
Hey! 

Saw your custom source exts PR landed in RN `0.45.0-rc.0`. Had been working on a similar PR myself some months ago, but never got it working properly. So, thanks for your great work!

Maybe I'm jumping ahead of the readiness of this transformer, but I had to try it out of course.

Just setting up a simple project (https://github.com/cbrevik/tsWithTransformer) I got the following error:
```
error: bundling: Error: Got at least one module with raw mappings, but /Users/cbrevik/Dev/TEMP/tsWithTransformer/src/app.tsx has a full source map
    at resolver.wrapModule.then (/Users/cbrevik/Dev/TEMP/tsWithTransformer/node_modules/react-native/packager/src/Bundler/Bundle.js:106:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Bundling `index.ios.js`  100.0% (392/392), failed.
Error: Got at least one module with raw mappings, but /Users/cbrevik/Dev/TEMP/tsWithTransformer/src/app.tsx has a full source map
    at resolver.wrapModule.then (/Users/cbrevik/Dev/TEMP/tsWithTransformer/node_modules/react-native/packager/src/Bundler/Bundle.js:106:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Just wondering if you got it working? Do you have any example projects? 

If you need any help testing or debugging, I'd be willing to help.

**Comment by ds300** [comment]
Funny, I was just testing this for the first time with 0.45.0-rc.0 today, and ran into the same issue.

Found a quick fix for that issue (force the `generateSourceMaps: true` transformer option, see the link in #1), but ran into a minor source map misalignment issue. Looking at it now. I'll hopefully update this repo very soon with a version that works well enough.

**Comment by ds300** [comment]
@cbrevik 1.0.3 seems to work. For some reason, the standard method of source map composition was not working, so I had to do it the manual way, but not 100% sure I did the right thing. Seems to work at least. If it works for you, feel free to close this issue.

I also updated the README with more useful setup instructions now that 0.45 is in the RC phase.

**Comment by cbrevik** [comment]
@ds300 fantastic, seemed to solve it for me as well. Thanks!

I've been looking at the Haul CLI as a potential way forward to handle TypeScript in React Native, but it seems to require too many parts. Hoping that instead your contributions will enable us to more easily use the original packager + minor customisations.

I'll dig some more into this now 👍

**Comment by cbrevik** [comment]
Actually I seem to have no source maps for any of my tsx-files when debugging from Chrome. Do you experience the same issue?

**Comment by ds300** [comment]
I didn't try that yet. Feel free to open another issue for it.
