### ISSUE TITLE
Error transforming

### ISSUE THREAD

**Issue by onselakin** [ds300/react-native-typescript-transformer#22]
Hey ds300,

Suddenly I started getting the error below while working with Expo:

```
Error: Uncaught error in the transformer worker: /Users/onselakin/Development/frontend/node_modules/react-native-typescript-transformer
    at _transform.then.catch.error (/Users/onselakin/Development/frontend/node_modules/react-native/packager/src/JSTransformer/index.js:124:33)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Any recommendations?

Thank you!

**Comment by ds300** [comment]
If you can create a repo which reproduces the issue I'll take a look. On first inspection it seems like this is not an issue with react-native-typescript-transformer throwing errors, because transformers are synchronous and their thrown errors are normally reported correctly in the packager log.

**Comment by onselakin** [comment]
Thanks for the reply. Looks like Expo got an update recently. I got it to work after installing Typescript into local repo.
