### ISSUE TITLE
Add note in README about using absolute paths for source modules

### ISSUE THREAD

**Issue by ds300** [ds300/react-native-typescript-transformer#25]
I think a lot of people use absolute paths these days and it is not clear that both typescript and react-native (and maybe jest or some other test framework) need to be configured independently to support them. As evidenced by #24

**Comment by agarcia17** [comment]
anybody got the absolute paths working?

**Comment by ds300** [comment]
Yes it's fairly simple.

In tsconfig.json:

```patch
 {
   "compilerOptions": {
+    "baseUrl": "."
   }
 }
```

And then for react-native, you need to add one or more `package.json` files. These only need to contain the `"name"` field, and should be placed into any folders in the root of your project that you want to reference with an absolute path. The `"name"` field's value should be the name of the folder.  So for me, I just added one file at `src/package.json` with the contents `{"name": "src"}`.

Then if you use jest, add the following in your root package.json:

```patch
 {
   "jest" {
+     "modulePaths": ["<rootDir>"]
   }
 }
```

And you should be good to go. e.g. for the folder structure

```
<rootDir>
├── src
│   ├── package.json
│   ├── App.tsx
│   ├── components
│   │   ├── Banana.tsx
│   ├── index.tsx
├── package.json
├── tsconfig.json
```

you can, e.g. `import Banana from 'src/components/Banana'` from any .ts(x) file

Thanks for reminding me to put this in the Readme, and let me know if you run into any issues with the instructions.
