### ISSUE TITLE
Components written in TS has no source maps in Chrome debugger

### ISSUE THREAD

**Issue by cbrevik** [ds300/react-native-typescript-transformer#3]
Project which reproduces this issue is located [here](https://github.com/cbrevik/tsWithTransformer/tree/20e7dcb07a020d436f0af7fc15cb419c90191f6e).

JavaScript files (for example my `index.ios.js` entry point) has source maps. But my `.tsx` files are blank in Chrome debugger:
![image](https://cloud.githubusercontent.com/assets/4932625/26023603/2ecc31de-37c0-11e7-9aa2-9a66d8dba7b7.png)

**Comment by ds300** [comment]
1.0.4 should fix this :) Please re-open the issue if it didn't.

**Comment by cbrevik** [comment]
That did indeed fix it, thanks! :)

**Comment by lukewis** [comment]
@cbrevik How did you get your tsx files to show up in the chrome debugger in the first place?  I've been googling for hours on this but coming up blank.  Are you able to point me in the right direction?
