### ISSUE TITLE
Compiler does not report error when compiling

### ISSUE THREAD

**Issue by yuwenhuisama** [ds300/react-native-typescript-transformer#35]
For react native, when there are compile errors, ts still dose not report them while tslint has marked them.

**Comment by ds300** [comment]
Can you give an example? Syntax errors should be reported, but lint and type errors are not expected to be reported. See #13 for more details about why.

**Comment by yuwenhuisama** [comment]
Well, what I expect is exactly to report the type errors not only syntax errors, I wish this could be a feature to implement as an option.

**Comment by RubenSandwich** [comment]
@yuwenhuisama One way to get that feature is to use: https://github.com/callstack/haul. Which is a replacement for the React Native Packager. They have a typescript setup example: https://github.com/callstack/haul/blob/master/docs/Recipes.md.

**Comment by ds300** [comment]
I'm going to close this issue because it's a duplicate of #29 — if you feel this is a separate issue, please feel free to open another issue and link to this one :pray:
