### ISSUE TITLE
Fix source mapping in react-native 0.52

### ISSUE THREAD

**Issue by ds300** [ds300/react-native-typescript-transformer#39]
following discussion from from #37

**Comment by dluksza** [comment]
Configuration for running jest tests described in https://github.com/ds300/react-native-typescript-transformer/issues/21#issuecomment-330148700 also doesn't work with 0.52

**Comment by ds300** [comment]
Ah yes, that makes sense. Thanks for the heads-up! I'm going to try duplicating the old upstream transformer locally.

**Comment by ds300** [comment]
Another thing I'm trying is traversing the ast and updating its mappings in place. Seems doable so far.

**Comment by dluksza** [comment]
Jest tests are still failing with the same error as mentioned in my previous comment :|

**Comment by ds300** [comment]
Ah yes. I should have made another

**Comment by ds300** [comment]
@dluksza you can do this for now:

```
var tsTransformer = require('react-native-typescript-transformer')
var rnTransformer = require('react-native/jest/preprocessor')
var generate = require('babel-generator')

var preprocessor = Object.assign({}, rnTransformer, {
  process (src, file) {
    const {ast} = tsTransformer.transform({
      filename: file,
      localPath: file,
      options: {
        dev: true,
        platform: '',
        projectRoot: '',
      },
      src,
    })

    return generate.default(ast, {
      filename: file,
      retainLines: true
    }, src)
  },
})

module.exports = preprocessor
```

It doesn't do source mapping, but then neither did the original version.

**Comment by dluksza** [comment]
@ds300 thank you that works! :D
