### ISSUE TITLE
Error "React is not defined" if importing component from another folder

### ISSUE THREAD

**Issue by cbrevik** [ds300/react-native-typescript-transformer#4]
Getting the following error if I move `Button.tsx` down a folder to `./src/components/` and importing it from `./src/index.tsx`:
![image](https://cloud.githubusercontent.com/assets/4932625/26025646/55e5f936-37ec-11e7-89af-e75d80b0ff24.png)
Relevant reproducible code [here](https://github.com/cbrevik/tsWithTransformer/tree/a070516381ccf9aeffdfe0292e01b52e62cefbe4).

If I place `Button.tsx` next to `index.tsx` in `./src`, it works fine. As [here](https://github.com/cbrevik/tsWithTransformer/tree/fefdec5aeeb9ffdc95490e04873a62eab7e45eb3).

**Comment by ds300** [comment]
a070516381ccf9aeffdfe0292e01b52e62cefbe4 is working fine for me :thinking:

Did you try resetting your packager cache? `yarn start -- --reset-cache`?

**Comment by cbrevik** [comment]
Aw shit, you're correct. Resetting cache like that solved it. Tried a lot of other things before reporting, sorry!
