### ISSUE TITLE
Absolute paths, tsc complains it can't find the module

### ISSUE THREAD

**Issue by AleskiWeb** [ds300/react-native-typescript-transformer#56]
Using this package with vs-code and when I am importing via the absolute path using the package.json file it tells me it can't find it. It still transpiles and works but it's kind of annoying.

I've seens some solutions include an index.d.ts file and declare the module there, for example:

In app.tsx
`import HeaderComponent from 'src/HeaderComponent`

In same folder as the `package.json { "name": "src"}` named `index.d.ts`
`declare module src { ... }`

However I'm not getting much luck with it. Have you ran into such an IDE complaint before?

**Comment by ds300** [comment]
Hi!

I haven't run into that issue before. Did you make sure the `baseUrl` property is set in tsconfig.json?

See [here](https://github.com/ds300/react-native-typescript-transformer#typescript) for an example.

**Comment by AleskiWeb** [comment]
I have yeah, like I said, it compiles and works but when I run `tsc` it tells me it can't find that module. Have you used the `paths` compiler option before? Seems to be a work around (for ts files atleast) to provide absolute paths.

**Comment by ds300** [comment]
Hmm the `baseUrl` property should take care of that, there should be no need for `paths`. Can I see your tsconfig, an illustration of your directory structure, and an example of an import statement that's not working?

**Comment by Slessi** [comment]
I have the same issue. In my tsconfig I use

```json
"baseUrl": "./",
"paths": {
    "@src/*": ["src/*"]
}
```

But neither of the following work when importing `./src/styles.ts` inside file `./src/App.tsx`:

```ts
import { styles } from "@src/styles";
import { styles } from "src/styles";
``` 

Relative import continues to work
```ts
import { styles } from "./styles";
```

Worth nothing that `tsc` manages to compile the file when using any of the above 3 imports

**Comment by Slessi** [comment]
@ds300 adding `{"name": "src"}` to `src/package.json` does make `src/styles` work, but really I prefer the combination of `index.ts` files and `baseUrl` and `paths`

**Comment by ds300** [comment]
Cool, let me know if you find a way to make react-native work with that setup!

**Comment by ds300** [comment]
I'm going to close this issue due to inactivity. Please open a new issue and link to this one if you're still having trouble with absolute paths! :pray:

**Comment by olegsmetanin** [comment]
How to avoid 'src' in imports?
import HeaderComponent from 'nav/HeaderComponent' // without src/ in path

**Comment by devprakashbinary** [comment]
still I have same issue absolute path is not working even I have make the required changes in tsconfig.json as well as add package.json file in my app folder

**Comment by technoplato** [comment]
@Meligy solution worked for me with WebStorm 👍
