### ISSUE TITLE
Can you update source-map to improve performance?

### ISSUE THREAD

**Issue by sunnylqm** [ds300/react-native-typescript-transformer#57]
https://github.com/mozilla/source-map/blob/master/CHANGELOG.md
`SourceMapConsumer` now uses WebAssembly, which is much faster

**Comment by ds300** [comment]
Absolutely!

**Comment by ds300** [comment]
I ran into an issue with this and submitted a PR to source-map to fix it https://github.com/mozilla/source-map/pull/330 — will try again once that gets published.

**Comment by ds300** [comment]
Sweet, thanks for the heads up! I'll take a look soon.

**Comment by ds300** [comment]
Just published `react-native-typescript-transformer@1.2.6` with the new `source-map` 🎉

**Comment by ds300** [comment]
I decided to revert this change. It broke some people's builds already, and would probably break some more in the coming weeks. I don't think the perf improvements from wasm are worth the time and effort required from the people this affects. Maybe I'll try again in a while.
