### ISSUE TITLE
"Unexpected token '.'" error when using whatwg-url

### ISSUE THREAD

**Issue by Fitzpasd** [ds300/react-native-typescript-transformer#60]
When using the popular library [whatwg-url](https://www.npmjs.com/package/whatwg-url), I get this unhelpful error:

![screenshot-1524677787605](https://user-images.githubusercontent.com/1279954/39262539-83fbf214-4874-11e8-8182-46aecc9e138e.jpg)

I narrowed it down to this library by commenting out code locally.  In the end, this is the cause:

```
import { URL } from "whatwg-url";
...
const url = new URL("https://github.com");
```

Without that code, no error occurs.  It's also interesting to note that if you're debugging via Chrome, this error doesn't occur.

**Comment by luisnaranjo733** [comment]
I'm also hitting this

**Comment by Fitzpasd** [comment]
Thanks for the extra info!  I'll find an alternative lib :)

**Comment by ds300** [comment]
Another link I found seems to imply that the JSC bug was fixed late last year but I guess RN hasn't caught up: https://bugs.webkit.org/show_bug.cgi?id=157970#c17
