### ISSUE TITLE
Ignoring "outDir" from tsconfig.json

### ISSUE THREAD

**Issue by jasin755** [ds300/react-native-typescript-transformer#61]
react-native-typescript-transformer ignore `outDir` defined in my `tsconfig.json`

`tsconfig.json`:
```
{
    "compilerOptions": {
        "target": "es2015",
        "module": "es2015",
        "jsx": "react-native",
        "moduleResolution": "node",
        "allowSyntheticDefaultImports": true,
        "experimentalDecorators": true,
        "noImplicitAny": true,
        "strict": true,
        "outDir": "./artifacts"
    }
}
```

and `rn-cli.config.js`

```
module.exports = {
    getTransformModulePath() {
        return require.resolve('react-native-typescript-transformer');
    },
    getSourceExts() {
        return ['ts', 'tsx'];
    }
}
```

I use this command:
`/usr/local/bin/node /usr/local/lib/node_modules/react-native-cli start --config /Users/xxxxx/WebstormProjects/untitled2/rn-cli.config.js` to start app and typescript files always compile to same place where is original `ts/tsx` file

**Comment by ds300** [comment]
I'm going to close this issue due to inactivity. If you're still having trouble with compilation, please feel free to open another issue and link to this one :pray:


Thanks for fielding this one, @aMarCruz 🙌
