### ISSUE TITLE
1.2.7 is breaking on Node9+

### ISSUE THREAD

**Issue by ygorlazaro** [ds300/react-native-typescript-transformer#64]
Hi,

this last release is running an error using Node 9. While debugging we saw this error running from our CI, pointing to your lasted release.

My solution was rollback to 1.2.3 version.

**Comment by ds300** [comment]
Hi! 👋 Thanks for the report! What was the error message?

**Comment by ygorlazaro** [comment]
This is the message I got:

```
output info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
output error react-native-typescript-transformer@1.2.7: The engine "node" is incompatible with this module. Expected version ">=8.0.0".
output error Found incompatible module
output info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
output 19:56:26 [exp] Unable to find an existing exp instance for this directory, starting a new one...
output 19:56:29 [exp] Error: node_modules directory is missing. Please run `npm install` in your project directory.
```

**Comment by ygorlazaro** [comment]
I'm using v9.9.0

**Comment by ds300** [comment]
😕🤔 I will look into this tomorrow.

**Comment by ygorlazaro** [comment]
No problems, man. I'll see if I could help you on this!

**Comment by ygorlazaro** [comment]
@ds300 , is there a reason to use `"engineStrict": false`? I know you want to mark this a required, since now the lib supports WASM, but can't it just be a warning setting `engineStrict` as false?

**Comment by ds300** [comment]
Yeah I'll do that. I'm pretty sure `">=8.0.0"` is correct syntax, so this is really baffling. But I suppose an erroneous warning is better than an erroneous error.

**Comment by ds300** [comment]
alright, just publushed 1.2.8 without engineStrict!

**Comment by ygorlazaro** [comment]
Great, I'll try right now! Thanks!

**Comment by ygorlazaro** [comment]
It worked. Sorry the delay to answer you
