### ISSUE TITLE
lint-staged and husky should be a dev-dependency, not a dependency

### ISSUE THREAD

**Issue by cliffkoh** [ds300/react-native-typescript-transformer#8]
Hi,

Fairly sure lint-staged and husky should be a dev-dependency, not a dependency... Could you confirm? Should be easy to fix and happy to create a PR if that helps.

Thanks!

**Comment by ds300** [comment]
Quite right, thanks for the heads-up 👍

**Comment by cliffkoh** [comment]
Thank you for the fast fix :+1:
